version: '2.13.0'

volumes:
    volvueapi:
    dbdata:

services:
  # nginx:
  #   restart: always
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - my-network-name
  db:
    restart: always
    image: mysqlanddata:latest
    container_name: db
    environment:
      # MARIADB_ROOT_PASSWORD: sumoh            
      MYSQL_ROOT_PASSWORD: sumoh
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_HOST: '%'
    ports:      
      - 3306:3306    
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql      
    mem_limit: 512m
    networks:
      - my-network-name                
    command: --default-authentication-plugin=mysql_native_password    

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1    
      VIRTUAL_HOST : database.betflix4you.co
      VIRTUAL_PORT : 9000
    ports:
      - 9000:80
    expose:
      - 9001
    mem_limit: 512m
    networks:
      - my-network-name
    depends_on:
      - db

  vueapi:
    restart: always
    image: vueapi:latest
    container_name: vueapi
    environment:
      NODE_ENV: production
      MYSQL_HOST: db 
      MYSQL_PORT: 3306 
      MYSQL_USER: root
      MYSQL_PASSWORD: sumoh
      MYSQL_DATABASE: app_db
      VIRTUAL_HOST : api.betflix4you.co
      VIRTUAL_PORT : 9500
    ports:
      - 9500:9500
    expose:
      - 9500
    volumes:
        - ./vueapi:/vueapi
        - /vueapi/node_modules
    mem_limit: 512m
    networks:
      - my-network-name   

  vuemember:
    restart: always
    image: vuemember:latest
    container_name: vuemember 
    ports:
      - 8800:8800
    expose:
      - 8800
    environment:
      VIRTUAL_HOST : member.betflix4you.co
      VIRTUAL_PORT : 8800
      BASE_API_URL : 'http://api.betflix4you.co/'
      PORT : 8800
    volumes:
      - ./vuemember:/vuemember
      - /vuemember/node_modules  
    mem_limit: 512m
    networks:
      - my-network-name

  # vueadmin:
  #   restart: always
  #   image: vueadmin:latest
  #   container_name: vueadmin 
  #   ports:
  #     - 9900:9900
  #   expose:
  #     - 9900
  #   environment:
  #     VIRTUAL_HOST : admin.betflix4you.co
  #     VIRTUAL_PORT : 9900
  #     BASE_API_URL : 'http://api.betflix4you.co/'
  #     PORT : 9900
  #   mem_limit: 512m
  #   volumes:
  #     - ./vueweb:/vueweb
  #     - /vueweb/node_modules  
  #   networks:
  #     - my-network-name
    
networks:
  my-network-name:
   name: my-global-net

# volumes:  
#   dbdata:
#     driver: bridge  
#   vueapi:
#     driver: bridge  